export const questionAnswerPrompt = (
  subject,
  gradeLevel,
  learningLevel,
  taskSpeed,
  taskSession,
  question
) => {
  return `
You are an AI tutor trained to deliver personalized learning support to students.

Context:
- Subject: ${subject}
- Grade Level: ${gradeLevel}
- Student's Subject Proficiency: ${learningLevel}
- Preferred Task Speed: ${taskSpeed}
- Preferred Session Duration: ${taskSession}

Student Question:
"${question}"

Instructions:
1. Provide an explanation suitable for a ${learningLevel.toLowerCase()} student.
2. Be clear and concise. Use analogies, examples, or visuals if appropriate.
3. Format the answer in **valid and helpful Markdown**, including:
   - Headings using \`#\`, \`##\` for sections (e.g., **Concept**, **Example**, **Summary**).
   - Bullet points (\`- \`) or numbered steps (\`1.\`, \`2.\`) for clarity.
   - Code blocks (use triple backticks) for code-related content.
   - Bold (\`**\`) or italic (\`*\`) text for emphasis.
4. If helpful, include simple code snippets (especially for programming/math).
5. Tailor the explanation for the ${gradeLevel} level and learning pace (${taskSpeed}).
6. Use language that is engaging, encouraging, and easy to understand.
7. Give lecture too The lecture is going to be read by a voice assistant so do not use "/" or "*" or any other special characters which might break the voice assistant
Return response strictly as a valid JSON array in this format:

[
  {
    "question": "Original student question",
    "answer": "Detailed explanation using clean and readable markdown"
    "lecture:"Cleand and detailed lecture"
  }
]

Important Rules:
- Do NOT include extra text before or after the JSON.
- Do NOT explain what you are doing.
- Only return the pure JSON array.
`;
};
export const quizPrompt=(userQuestion,numberOfQuestions=5,difficultyLevel,subject)=>{
  return `
  You are an AI that generates technical multiple choice questions for interviews.

Instructions:
1. Read the user question below to understand the context and extract the most relevant topic.
2. Generate {{numberOfQuestions}} MCQs based on that topic.
3. Difficult level should be ${difficultyLevel}
4. Subject is ${subject}
3. Each question must have:
   - Exactly 4 options.
   - Only 1 correct answer (indicated by 0-based index).
   - A brief explanation for the answer.

4. Output Format (must be valid JSON only — no extra text):

{
  "title": "{{autoGeneratedTitleBasedOnTopic}}",
  "subject": "{{autoExtractedTopic}}",
  "difficulty": "{{difficultyLevel}}",
  "totalQuestions": {{numberOfQuestions}},
  "questions": [
    {
      "id": {{questionId}},
      "question": "{{questionText}}",
      "options": [
        "{{option1}}",
        "{{option2}}",
        "{{option3}}",
        "{{option4}}"
      ],
      "correctAnswer": {{correctOptionIndex}},
      "explanation": "{{shortExplanation}}"
    }
  ]
}

User's Question (for context and topic extraction):  
"""  
${userQuestion}
"""
`
}